# TODO:
# 1. Create PAT with `read:packages` and `write:packages` see https://docs.github.com/en/free-pro-team@latest/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
# 2. Create CR_PAT variable under Settings / Secrets

name: TEST

on:
  push:
    branches:
    - main

env:
  FETCHER_IMAGE_VERSION: ""
  BASE_IMAGE_VERSION: ""
  
  # NOTE: DO NOT CHANGE THIS THIS IS TMP IMAGE NAME
  IMAGE_NAME: image

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build . \
           --build-arg FETCHER_IMAGE_VERSION=${FETCHER_IMAGE_VERSION} \
           --build-arg BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION} \
           --file Dockerfile --tag $IMAGE_NAME
